render-xelatex:
	xelatex report.tex
	biber report
	xelatex report.tex
	xelatex report.tex

clean:
	rm report.aux report.bbl report.bcf report.blg report.log report.out report.run.xml report.tex.bbl report.tex.blg report.toc texput.log
